### ISSUE TITLE
Common database locations on Windows

### ISSUE THREAD

**Issue by klieret** [klieret/AnkiPandas#1]
Where does Anki usually store it's database under Windows? 

This would be good to know in order to make it easy for ``AnkiPandas`` to find the databse automatically.

**Comment by mrswagbhinav** [comment]
I believe Anki saves its data to the Documents folder

**Comment by klieret** [comment]
Hi @mrswagbhinav 

Thanks for your comment :+1: 

Looks like getting these paths under Windows is a bit of a pain, but this should work (https://stackoverflow.com/questions/3858851/python-get-windows-special-folders-for-currently-logged-in-user/3858957)

```python3
import ctypes.wintypes
import path
CSIDL_PERSONAL= 5
SHGFP_TYPE_CURRENT= 0
buf = ctypes.create_unicode_buffer(ctypes.wintypes.MAX_PATH)
types.windll.shell32.SHGetFolderPathW(0, CSIDL_PERSONAL, 0, SHGFP_TYPE_CURRENT, buf)
path = pathlib.WindowsPath(buf.value)
print(path / "Anki2")
```

Could you confirm that this python snippet points to your Anki installation?

**Comment by exc4l** [comment]
Besides the typo (ctypes in line 6 instead of just types) this result in the documents folder.

But as you probably know, Anki isn't saving its data to the documents folder but to (using WIN 10)
```
C:\Users\USER_NAME\AppData\Roaming\Anki2\User 1
```
The current search is able to find the correct collection, but it checks an unnecessary amount of locations under windows. 

I haven't seen a different location under windows and several scripts that are shared in the anki community do have this path (even user 1 as a profile name) hardcoded.

**Comment by klieret** [comment]
Thanks a lot for even fixing this yourself! Very nice addition :)
