### ISSUE TITLE
sub- and superdeck support

### ISSUE THREAD

**Issue by geldbogen** [klieret/AnkiPandas#144]
Hey all, 
first comment here, so please don't burn me 😄 
I would like to suggest another field, called "superdeck", where one can see the highest level deck of the note. For example, if I have a note/card in the deck First Deck::Second Deck::Third Deck, it would show First Deck in this field.

Because I have a lot of subdecks in one deck, it makes it kind of tedious to analyze them properly.

Kind regards,

**Comment by geldbogen** [comment]
Hey @klieret, 
thanks for the fast answer. You may misunderstand me though, I know how to achieve this. However, maybe this would be a convenient column in the Ankidataframe because I think some people would be rather interested in analyzing their data with respect to the corresponding "superdeck" (don't know a better term for it) than w.r.t. the corresponding "subdeck".

Kind regards from Germany,
P.S.: I would like to contribute something to this addon if you have a most "urgent" issue let me know! :)

**Comment by klieret** [comment]
Hi @geldbogen, thanks for following up :) 

I think I'm still a bit confused. Because AnkiDataFrame is a subclass of a pandas DataFrame, the same code above should work for it (and then you can simply continue your analysis with the new column). Or are you suggesting that this should be added by default? I'd be a bit skeptical about adding derived columns to the dataframe, as this increases the complexity of the package. The main issue would be how to deal with changes to that column when writing back to the collection (because that would mean it's out of sync with the `cdeck` column).

Sending best regards to Germany :) 

I'd love to support contributions. I unfortunately have very little time to devote to this package these days. There are several urgent issues tied to writing back into the database: #137 , #50 , #32 (not sure if this is reproducible). We probably currently miss something there. This might require digging in the Anki source to see how they interface with the database.

A much easier (but also urgent) issue would be #143 (currently we require `pandas < 2.0` because of some changes introduced there).

**Comment by geldbogen** [comment]
Hey, 
,yeah basically I was asking to do this by default (i.e. computing the "superdeck"-column and adding it to the collection). 
But I was not aware of the issues arising with rewriting this in the anki library.  
But can't we just drop this column when the write method is called?
Anyway, thanks again for the fast response, I am going to have a look at the open issues you have mentioned. 
Don't worry about not having time, it is just for fun (and to improve my Python skills a bit)
Kind regards, yet again

**Comment by klieret** [comment]
>  But can't we just drop this column when the write method is called?

Yes, we could do this, but I feel like this would be more confusing to users: The `cdeck` column would affect the database, while the "first_deck" column doesn't. 

I'm also not sure how many users actually need this column, and it's easy enough to add...

But thank you for the suggestion :)
